#!/usr/bin/env bash
#
#
set -u -e -o pipefail

IS_TEST="yes" deno run \
  --allow-net=deno.land,raw.githubusercontent.com,api.github.com \
  --allow-run="touch,find,fd,ls,echo,node" \
  --allow-read="./,./tmp" \
  --allow-write="./tmp" \
  --allow-env=IS_TEST,NO_COLOR \
  spec/__.ts "$*"
